### ISSUE TITLE
Как дела?

### ISSUE THREAD

**Issue by Jnster** [Olzumzum/MyPerformance#1]
Как жизь?

**Comment by Olzumzum** [comment]
о что я увидела

**Comment by Olzumzum** [comment]
> Как жизь?

да что? делаю потихоньку. сгорает жопа с библиотеки графиков, с ней основная морока, а так все ок. у тебя как дела?

**Comment by Jnster** [comment]
> > Как жизь?
> 
> да что? делаю потихоньку. сгорает жопа с библиотеки графиков, с ней основная морока, а так все ок. у тебя как дела?

Лежу, проснулся
